server:
  port: 4433
spring:
  application:
    name: cloud-config-center
#    配置config配置中心
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiDongYang743/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
#      配置RibbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 注册到eureka注册中心
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka


# 配置消息总线
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'





