server:
  port: 8006
# consul服务端口号
spring:
  application:
    name: cloud-providerconsul-payment
# consul服务注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
